---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "aya-node.fullname" . }}
  labels:
    {{- include "aya-node.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: p2p
      protocol: TCP
      name: p2p
      {{- if and .Values.service.nodePort ( eq .Values.service.type "NodePort" )}}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    {{- include "aya-node.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "aya-node.fullname" . }}-internal
  labels:
    {{- include "aya-node.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    {{- if .Values.service.unsafeRpcExternalEnabled }}
    - port: {{ .Values.service.rpcPort }}
      targetPort: rpc
      protocol: TCP
      name: rpc
    {{- end }}
    - port: 9615
      targetPort: prom
      protocol: TCP
      name: prom
  selector:
    {{- include "aya-node.selectorLabels" . | nindent 4 }}
