{{ if .Values.monitoring.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "aya-node.serviceAccountName" . }}
  labels:
    {{- include "aya-node.labels" . | nindent 4 }}
    release: kube-prometheus-stack
spec:
  endpoints:
    - path: /metrics
      port: prom
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      {{- include "aya-node.labels" . | nindent 6 }}
{{ end }}
